columns:
- online_order
- book_table
- rate
- votes
- listed_in(type)
- cuisines
- cost
- listed_in(city)


drop_columns:
- url
- address
- name
- phone
- location
- dish_liked
- rest_type
- menu_item
- str_reviews_list
- mean_reviews_list
- reviews_list

numerical_cols:
- votes
- cost
